name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.10.2
        otp-version: 22.2
    - name: Cache dependencies directory
      uses: actions/cache@v1
      env:
        cache-name: cache-deps-directory
      with:
        path: deps
        key: ${{ runner.os }}-deps-${{ env.cache-name }}-${{ hashFiles('mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-deps-${{ env.cache-name }}-
          ${{ runner.os }}-deps-
    - name: Install Dependencies
      run: mix deps.get
    - name: Cache build directory
      uses: actions/cache@v1
      env:
        cache-name: cache-build-directory
      with:
        path: _build
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: |
          ${{ runner.os }}-build-
    - name: Compile
      run: mix compile
    - name: Check Format
      run: mix format --check-formatted
    - name: Check Style
      run: mix credo --strict
    - name: Run Tests
      run: mix test
    - name: Check Types
      run: mix dialyzer --halt-exit-status
